# Generated by Django 3.1 on 2021-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('calories', models.IntegerField()),
                ('instructions', models.TextField(max_length=1000)),
                ('ingredients', models.TextField(max_length=250)),
                ('time_to_make', models.IntegerField(default=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
