# Generated by Django 3.1 on 2021-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210509_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photos',
            field=models.ImageField(default='frontend/static/images/default.png', upload_to='frontend/static/images'),
        ),
    ]
