# Generated by Django 3.1 on 2021-06-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210606_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postanimals',
            name='photo',
        ),
    ]
