# Generated by Django 3.1 on 2021-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210612_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeuser',
            name='city',
        ),
        migrations.AlterField(
            model_name='postanimals',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postanimals',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='MakeBreed',
        ),
        migrations.DeleteModel(
            name='MakeCity',
        ),
    ]
