# Generated by Django 3.1 on 2021-06-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210612_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postanimals',
            name='user',
        ),
    ]
