# Generated by Django 3.1 on 2021-06-12 16:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_postanimals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanimals',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to=api.models.upload_to),
        ),
    ]
