# Generated by Django 3.1 on 2021-06-13 07:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_postanimals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanimals',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=api.models.upload_to),
        ),
    ]
