# Generated by Django 3.1 on 2021-06-19 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210613_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanimals',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
