# Generated by Django 3.1 on 2021-07-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210629_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='makecomments',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='makecomments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.postanimals'),
        ),
    ]
