# Generated by Django 3.1 on 2021-07-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210702_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makecomments',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='makecomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postanimals'),
        ),
    ]
